### ISSUE TITLE
Not linking stylsheets/JavaScript code

### ISSUE THREAD

**Issue by clownprinc98** [uxq/HTMLThor#11]
moreso for a best web practice, HTMLThor doesn't get upset when we don't link css and js code in other files.

**Comment by andyepx** [comment]
What does this mean?

**Comment by clownprinc98** [comment]
``` html
<script type="text/javascript">
// a whole bunch of code
</script>
```

Isn't it considered "better practice" to use:

``` html
<script type="text/javascript" src="js/myawesomecode.js"></script>
```

**Comment by simonghales** [comment]
If you have a small scale website with only a small amount of JavaScript it's better practice to include that JavaScript in `<script>` tags to reduce the number of http requests made to the server.

@clownprinc98 

@andyepx I don't know if you added this as a best practice warning, if you did can you make sure it's worded as "consider including your JavaScript externally" rather than "you should include your JS externally".
